apiVersion: v2
name: rest-api-helmdemo
description: A Helm chart for Kubernetes

# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 0.1.0

appVersion: "1.16.0"
